# Refer to golangci-lint's example config file for more options and information:
# https://golangci-lint.run/docs/configuration/file/
version: 2

run:
  timeout: 10m
  modules-download-mode: readonly
    
linters:
  enable:
    - errcheck
    - ineffassign
    - unused
    - revive
    - govet
    - staticcheck
    - gosec
    - misspell

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
