apiVersion: v1
kind: Service
metadata:
  name: acl-config
  labels:
    app: config-server
    component: config-api
spec:
  selector:
    app: config-server
  ports:
    - name: http
      port: 8181
      targetPort: 8383
      protocol: TCP
  type: ClusterIP
