apiVersion: v1
kind: Service
metadata:
  name: mcp-api-key-server
  namespace: mcp-test
  labels:
    app: mcp-api-key-server
spec:
  selector:
    app: mcp-api-key-server
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
