apiVersion: v1
kind: Service
metadata:
  name: mcp-config
  namespace: mcp-system
  labels:
    app: mcp-broker-router
    component: config-api
spec:
  selector:
    app: mcp-broker-router
    component: broker-router
  ports:
    - name: http
      port: 8181
      targetPort: 8181
      protocol: TCP
  type: ClusterIP
