servers:
  - name: test-server1
    url: http://localhost:9001
    hostname: server1.example.com
    enabled: true
    toolPrefix: "s1_"
  - name: test-server2
    url: http://localhost:9002
    hostname: server2.example.com
    enabled: true
    toolPrefix: "s2_"
