---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio: ingressgateway
  name: mcp-gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: mcp
      hostname: 'mcp.127-0-0-1.sslip.io' #public accessibly MCP host one used by client
      port: 8080
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: keycloak
      hostname: 'keycloak.127-0-0-1.sslip.io'
      port: 8080
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: mcps
      hostname: '*.mcp.test.com' # set to test.com on purpose to illustrate it doesn't matter what is in here but something has to be in here
      port: 8080
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
