apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mcpservers.mcp.kagenti.com
spec:
  group: mcp.kagenti.com
  names:
    kind: MCPServer
    listKind: MCPServerList
    plural: mcpservers
    singular: mcpserver
    shortNames:
    - mcpsrv
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=='Ready')].status
    - name: Targets
      type: string
      jsonPath: .spec.targetRefs[*].name
    - name: Prefix
      type: string
      jsonPath: .spec.toolPrefix
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    schema:
      openAPIV3Schema:
        type: object
        description: MCPServer defines a collection of MCP (Model Context Protocol) servers to be aggregated by the gateway. It enables discovery and federation of tools from multiple backend MCP servers through HTTPRoute references.
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            description: Spec defines the desired state of the MCPServer resource
            required:
            - targetRefs
            properties:
              targetRefs:
                type: array
                description: TargetRefs specifies HTTPRoutes that point to backend MCP servers. Each referenced HTTPRoute should have backend services that implement the MCP protocol.
                minItems: 1
                items:
                  type: object
                  required:
                  - group
                  - kind
                  - name
                  properties:
                    group:
                      type: string
                      default: gateway.networking.k8s.io
                      enum:
                      - gateway.networking.k8s.io
                      description: Group of the target resource
                    kind:
                      type: string
                      default: HTTPRoute
                      enum:
                      - HTTPRoute
                      description: Kind of the target resource
                    name:
                      type: string
                      description: Name of the HTTPRoute
                    namespace:
                      type: string
                      description: Namespace of the HTTPRoute (optional, defaults to same namespace)
                    toolPrefix:
                      type: string
                      description: Tool prefix for this specific server (overrides spec-level toolPrefix)
              toolPrefix:
                type: string
                description: ToolPrefix is the default prefix to add to all federated tools from referenced servers. This helps avoid naming conflicts when aggregating tools from multiple sources. Can be overridden per targetRef.
          status:
            type: object
            description: Status represents the observed state of the MCPServer resource
            properties:
              conditions:
                type: array
                description: Conditions represent the latest available observations of the MCPServer's state
                items:
                  type: object
                  required:
                  - type
                  - status
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
