name: Build Images

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  merge_group:
    types: [ checks_requested ]
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}   
            type=raw,value=latest,enable={{is_default_branch}}


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

   
      - name: Build and Push Image
        id: build-image
        uses: Wandalen/wretry.action@v3.8.0
        with:
          action: docker/build-push-action@v5
          with: |
            context: .
            file: ./Dockerfile
            platforms: linux/amd64,linux/arm64
            push: true
            provenance: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
          attempt_limit: 3          
          attempt_delay: 15000      
          time_out: 3600000         

     
